version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/ #S3에 있는 zip 파일이 EC2에 배포될 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart: #ApplicationStart 단계에서 deploy.sh를 실행
    - location: deploy.sh
      timeout: 60
      runas: ubuntu